services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "${APP_PORT}"
    depends_on:
      - db
    networks:
      - dockernet

  db:
    image: library/postgres:17
    container_name: ${POSTGRES_HOST}
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}"
    networks:
      - dockernet

#  test-db:
#    image: library/postgres:17
#    container_name: ${POSTGRES_HOST_TEST}
#    restart: always
#    environment:
#      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
#      POSTGRES_DB: ${POSTGRES_DB_TEST}
#    env_file:
#      - .env
#    ports:
#      - "${POSTGRES_PORT_TEST}:${POSTGRES_PORT_TEST}"
#    networks:
#      - dockernet

  nginx:
    image: nginx:1.27.3
    container_name: nginx_reverse_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - app
    networks:
      - dockernet

volumes:
  postgres_data:

networks:
  dockernet:
    driver: bridge
